### ISSUE TITLE
two bugs

### ISSUE THREAD

**Issue by wenxiang97** [ddmy/vue3-gantt#10]
作者的项目挺好用的，不过发现了几个问题:
1. schedule里的color设置为rgb会报错，npm的example跑不通；
2. 配置了repeatMode重叠属性后，exportGanttExcel会报错。

另外，schedule里的days必须是连续的时间，若该任务时间跨过周末就会中断。
通常后端返回的时间数据是以天为单位的对象，考虑days支持离散输入会不会方便许多，如days: ['2022-12-30', '2023-01-03', '2023-01-04']。或者更智能点days输入一个时间区间，渲染自动跳过周末和法定假日。
还有个小建议，可以新增个属性来让周六周日两列置灰，这样视觉会好些

**Comment by wenxiang97** [comment]
还有个小问题，下载后的excel打开后会提示 “部分内容有问题。是否让我们尽量尝试恢复? ”，不知道是不是系统问题。

**Comment by ddmy** [comment]
> 作者的项目挺好用的，不过发现了几个问题:
> 
> 1. schedule里的color设置为rgb会报错，npm的example跑不通；
> 2. 配置了repeatMode重叠属性后，exportGanttExcel会报错。
> 
> 另外，schedule里的days必须是连续的时间，若该任务时间跨过周末就会中断。 通常后端返回的时间数据是以天为单位的对象，考虑days支持离散输入会不会方便许多，如days: ['2022-12-30', '2023-01-03', '2023-01-04']。或者更智能点days输入一个时间区间，渲染自动跳过周末和法定假日。 还有个小建议，可以新增个属性来让周六周日两列置灰，这样视觉会好些

1. 关于周末的样式建议我觉得很棒，我会尽快实现它！法定节假日需要依赖服务端提供数据，这一点还需要再确认一下。
2. schedule下days现在支持区间的写法，但并不支持跳过周末（我会尽快支持这一功能）
3.  两个BUG 您能否提供一个最基础示例呢？

再次感谢支持！

**Comment by wenxiang97** [comment]
1. 关于schedule下days，其实项目中也不太需要前端来判断实际的工作日，后端一般会将每一天都返回，而不是返回一个区间，如{data: [{day: 1-9, ...},{day: 1-10, ...},{day: 1-12, ...}, {day: 1-13, ...}]}，即有可能一个任务在工作日也会有间断。所以我的意思 是不是让schedule下的days支持[1-9, 1-10, 1-12, 1-13]会更普适，否则得将其拆分成两个子任务，即days: [1-9, 1-10] 和days: [1-12, 1-13]，但一个任务后端只返回一个id，所以就有些难处理。
2.  基础示例就是 https://www.npmjs.com/package/vue3-gantt 的eg. 
     onMount(()=>exportGanttExcel())，报错：
     "Uncaught (in promise) Error: 转换色值格式错误:rgb(253, 211, 172)"。
     
     将rgb改为十六进制就可以正常下载了，但若配置const repeatMode = ref({ mode: 'extract'})，报错:
     "TypeError: Cannot read properties of undefined (reading 'replace')"

**Comment by ddmy** [comment]
- 目前已经支持配置不同格式的色值
- 周六日特殊展示这个我考虑到不同使用人群，以及国内周六日可能会有调休及不同假期，我觉得在以后开放渲染接口，让使用者能高度自定义配置的方案会更妥当一些
