### ISSUE TITLE
请问在日程的显示条上，点击如何获取当前格子的日期呢?

### ISSUE THREAD

**Issue by majingtao** [ddmy/vue3-gantt#20]
请问在日程的显示条上，点击如何获取当前格子的日期呢?[](url)

**Comment by ddmy** [comment]
感谢🙏
点击当前格子， 会触发`scheduleClick `事件，该事件接受一个包含日期信息的参数。说明文档里面有些。

**Comment by majingtao** [comment]
比如在6.30-7.5的日程里,点击7.2 或7.3的时候拿到的日期，一直是第一个格子的日期,  
{type: 'works', date: '2023-06-30', width: 550, left: 0, id: '1674344695524532226', …}
![1688091510914](https://github.com/ddmy/vue3-gantt/assets/4820861/9ff79cb9-ed7c-4ca2-a4d9-a8e1f74d2f02)

**Comment by ddmy** [comment]
当前甘特图会将日程信息 的格子合成一个，所以获取日程内具体点击的信息会有一些难度。
我这边刚刚更新了`vue3-gantt`版本 #21 
你先更新一下依赖到最新版本`1.1.8-3`😊。
然后最新的 scheduleClick 点击事件 参数重包含了原始的event 信息，你可以通过 `offsetX `属性获取点击的横向坐标。
`days`是一个数组，包含了当前块的所有日期，结合这两个属性，可以快速计算出当前点击坐标所代表的具体日期。


如果还有疑问，欢迎继续提问，非常感谢你的支持❤️
